create table notes (
    id integer primary key generated by default as identity,
    name text not null,
    modified timestamp default now() not null,
    content text,
    folderId integer references folders(id) on delete cascade not null
)